baseURL = 'https://splendid-bonbon-cd8e2b.netlify.app/'
languageCode = 'en-us'
title = 'West 104 Street Garden'
# theme = "eureka"
theme = "ananke"

hierarchicalCategories = true
background_color_class = "bg-blue"

[params]
# site_logo = "images/logo.jpeg"
custom_css = ["custom.css"]

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/west104garden/"

[[params.ananke_socials]]
name = "slack"
url = "https://join.slack.com/t/west104garden/shared_invite/zt-19vhpyl3p-3dQLzYvtBpG0VxkUybiCeA"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/west104streetgarden/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/west104garden/hugo-website"