[context.production.environment]
HUGO_VERSION = "0.99.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "16.15.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.99.1"


[build]
publish = "public"
command = "hugo --gc --minify"